name: Artifact

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Get Info 
        run: | 
          echo "id=$(jq -r '.id' module.json)" >> $GITHUB_OUTPUT
        id: info
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          chmod +x ./pack.sh
          ./pack.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.info.outputs.id }}
          path: deploy