name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Zip
        run: sudo apt-get install zip
      - name: Get Info 
        run: |
          echo "version=$(jq -r '.version' module.json)" >> $GITHUB_OUTPUT
          echo "id=$(jq -r '.id' module.json)" >> $GITHUB_OUTPUT
        id: info
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          chmod +x ./pack.sh
          ./pack.sh
          mv deploy/onlyoffice ${{ github.workspace }}/onlyoffice
      - name: Pack Artifact
        run: zip -r ${{ steps.info.outputs.id }}.zip onlyoffice
      - name: Release Artifact
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          artifacts: "${{ steps.info.outputs.id }}.zip"
          bodyFile: "RELEASE.md"
          tag: v${{ steps.info.outputs.version }}